spring:
  application:
    name: projectmanagement
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    property-naming-strategy: SNAKE_CASE
  mail:
    host: smtp.gmail.com
    port: 587
    username: tanh11704@gmail.com
    password: ohwk czxf pzvr lsbn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

cloudinary:
  url: cloudinary://374243676686272:uG_J9b9OE4_nRTJTCe7ZkPyR7gQ@dobtgdvzk

jwt:
  secret-key: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  expiration-ms: 900000 # 15 minutes
seeder:
  admin:
    email: admin@gmail.com
    password: 123456

cors:
  allowed-origins: http://localhost:5173

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # Sắp xếp operations theo HTTP method (GET, POST, PUT, DELETE...)
    operations-sorter: method
    # Sắp xếp tags theo thứ tự alphabet
    tags-sorter: alpha
    # Không mở rộng operations mặc định (none, list, full)
    doc-expansion: none
    # Hiển thị thời gian xử lý request
    display-request-duration: true
    # Bật tính năng lọc API
    filter: true
    # Hiển thị URL của API
    show-url: true
    # Hiển thị thông tin về request headers
    show-request-headers: true
  # Tắt hiển thị actuator endpoints
  show-actuator: false
  # Cấu hình mặc định cho tất cả các paths
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
